"""
generate_union_models.py

Generates dbt intermediate union models that combine staging models across
multiple source variants (e.g. regions) using the fabric_union_relations macro.

For each shared entity across variants, generates one model:
    int_<base_source>__<entity>_all.sql

Example:
    Sources: qad_us, qad_ca, qad_au (all have an 'ac_mstr' table)
    Generates: models/intermediate/qad/int_qad__ac_mstr_all.sql

    Which contains:
        {%- set relations = [ref('stg_qad_us__ac_mstr'), ref('stg_qad_ca__ac_mstr'), ref('stg_qad_au__ac_mstr')] -%}

        {{ fabric_union_relations(
            relations=relations,
            source_values=['qad_us', 'qad_ca', 'qad_au'],
            source_column_name='source_system',
            text_collation='Latin1_General_100_CI_AS_KS_WS_SC_UTF8'
        ) }}

Requirements:
    - fabric_union_relations macro must exist in your dbt project (macros/)
    - Source YAML files must exist (generated by generate_source.py)
    - Source naming convention: _source_<base>_<variant>.yml
      e.g. _source_qad_us.yml, _source_qad_ca.yml, _source_qad_au.yml

Usage:
    # Generate union models for all qad variants found under models/staging/
    python scripts/generate_union_models.py qad

    # Preview what would be generated without writing files
    python scripts/generate_union_models.py qad --dry-run

    # Overwrite existing models
    python scripts/generate_union_models.py qad --overwrite

    # Use a custom source column name
    python scripts/generate_union_models.py qad --source-column-name region

    # Use a custom collation
    python scripts/generate_union_models.py qad --collation Latin1_General_BIN2
"""

import os
import sys
import re
import argparse
import textwrap
from pathlib import Path

import yaml


# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

DEFAULT_COLLATION = "Latin1_General_100_CI_AS_KS_WS_SC_UTF8"


# ---------------------------------------------------------------------------
# Source file discovery
# ---------------------------------------------------------------------------

def find_source_files(base_source: str) -> list[Path]:
    """
    Discovers all source YAML files matching _source_<base_source>_<variant>.yml
    under models/staging/.

    Requires at least one character after the base source name and an underscore
    separator — so _source_qad.yml does not match, only _source_qad_<variant>.yml.
    This prevents accidentally picking up a consolidated single-source file.
    """
    staging_root = Path("models") / "staging"
    pattern = re.compile(
        rf"^_source_{re.escape(base_source)}_(\w+)\.yml$",
        re.IGNORECASE,
    )

    found = []
    for path in sorted(staging_root.rglob("*.yml")):
        if pattern.match(path.name):
            found.append(path)

    return found


def extract_variant(base_source: str, source_file: Path) -> str:
    """
    Extracts the variant suffix from a source filename.

    e.g. base_source='qad', filename='_source_qad_us.yml' -> 'qad_us'

    Returns the full source name (base + variant) rather than just the variant
    suffix, since this is what populates source_values in the generated macro call.
    """
    pattern = re.compile(
        rf"^_source_{re.escape(base_source)}_(\w+)\.yml$",
        re.IGNORECASE,
    )
    match = pattern.match(source_file.name)
    if not match:
        raise ValueError(
            f"Could not extract variant from filename '{source_file.name}' "
            f"using base source '{base_source}'."
        )
    variant = match.group(1).lower()
    return f"{base_source}_{variant}"


# ---------------------------------------------------------------------------
# Entity grouping
# ---------------------------------------------------------------------------

def load_entity_groups(
    base_source: str,
    source_files: list[Path],
) -> dict[str, list[tuple[str, str]]]:
    """
    Reads all source YAML files and groups tables by entity name across variants.

    Returns a dict of:
        {entity_name: [(source_name, staging_model_name), ...]}

    Example:
        {
            'ac_mstr': [
                ('qad_us', 'stg_qad_us__ac_mstr'),
                ('qad_ca', 'stg_qad_ca__ac_mstr'),
                ('qad_au', 'stg_qad_au__ac_mstr'),
            ],
        }

    Only entities that appear in more than one variant are included —
    unioning a single source is a no-op. Single-variant entities are
    reported so the caller is aware.
    """
    all_pairs: dict[str, list[tuple[str, str]]] = {}

    for source_file in source_files:
        if not source_file.exists():
            print(f"Warning: source file not found, skipping: {source_file}")
            continue

        try:
            source_name = extract_variant(base_source, source_file)
        except ValueError as e:
            print(f"Warning: {e}")
            continue

        with open(source_file, "r", encoding="utf-8") as f:
            data = yaml.safe_load(f) or {}

        for source in data.get("sources", []):
            for table in source.get("tables", []):
                entity = table.get("name", "").strip().lower()
                if not entity:
                    continue

                staging_model = f"stg_{source_name}__{entity}"

                if entity not in all_pairs:
                    all_pairs[entity] = []
                all_pairs[entity].append((source_name, staging_model))

    # Separate multi-variant entities from single-variant ones
    multi_variant = {}
    single_variant = []

    for entity, pairs in sorted(all_pairs.items()):
        if len(pairs) > 1:
            multi_variant[entity] = sorted(pairs)
        else:
            single_variant.append(entity)

    if single_variant:
        print(
            f"Note: {len(single_variant)} entity/entities only appear in one variant "
            f"and will be skipped (no union needed): {', '.join(single_variant)}"
        )

    return multi_variant


# ---------------------------------------------------------------------------
# SQL generation
# ---------------------------------------------------------------------------

def generate_union_sql(
    staging_models: list[str],
    source_values: list[str],
    source_column_name: str,
    collation: str,
) -> str:
    """
    Generates a dbt intermediate model using the fabric_union_relations macro.

    Relations and source_values are kept in the same order so each row's
    source_system value correctly identifies which staging model it came from.

    The relations list is assigned to a variable first to keep the macro call
    readable regardless of how many variants are being unioned.
    """
    ref_calls = ", ".join([f"ref('{model}')" for model in staging_models])
    source_vals = ", ".join([f"'{v}'" for v in source_values])

    return (
        f"{{%- set relations = [{ref_calls}] -%}}\n"
        f"\n"
        f"{{{{ fabric_union_relations(\n"
        f"    relations=relations,\n"
        f"    source_values=[{source_vals}],\n"
        f"    source_column_name='{source_column_name}',\n"
        f"    text_collation='{collation}'\n"
        f") }}}}\n"
    )


# ---------------------------------------------------------------------------
# Main logic
# ---------------------------------------------------------------------------

def generate_union_models(args: argparse.Namespace) -> None:
    base_source = args.base_source.lower()

    # --- Discover source files ---
    source_files = find_source_files(base_source)
    if not source_files:
        print(
            f"Error: No source YAML files found matching '_source_{base_source}_<variant>.yml' "
            f"under models/staging/. Run generate_source.py first.",
            file=sys.stderr,
        )
        sys.exit(1)

    print(f"Found {len(source_files)} source file(s):")
    for f in source_files:
        print(f"  {f}")
    print()

    # --- Load and group entities ---
    entity_groups = load_entity_groups(base_source, source_files)
    if not entity_groups:
        print(
            "Error: No entities found that appear in more than one source variant. "
            "Nothing to union.",
            file=sys.stderr,
        )
        sys.exit(1)

    print(f"Found {len(entity_groups)} entity/entities to union:\n")
    for entity, pairs in sorted(entity_groups.items()):
        print(f"  {entity}:")
        for source_name, model in pairs:
            print(f"    ref('{model}')  ->  source_system = '{source_name}'")
    print()

    if args.dry_run:
        print("Dry run — no files written.")
        return

    # --- Write model files ---
    output_dir = Path("models") / "intermediate" / base_source
    output_dir.mkdir(parents=True, exist_ok=True)

    created = []
    skipped = []

    for entity, pairs in sorted(entity_groups.items()):
        staging_models = [model for _, model in pairs]
        source_values = [source_name for source_name, _ in pairs]
        model_name = f"int_{base_source}__{entity}_all"
        model_path = output_dir / f"{model_name}.sql"

        if model_path.exists() and not args.overwrite:
            print(f"  Skipping {model_name} (already exists, use --overwrite to replace)")
            skipped.append(model_name)
            continue

        sql = generate_union_sql(
            staging_models=staging_models,
            source_values=source_values,
            source_column_name=args.source_column_name,
            collation=args.collation,
        )

        with open(model_path, "w", encoding="utf-8") as f:
            f.write(sql)

        print(f"  Generated {model_path} ({len(staging_models)} variants)")
        created.append(model_name)

    # --- Summary ---
    print(
        f"\nDone. Created: {len(created)}, Skipped: {len(skipped)}\n"
        f"Output directory: {output_dir}"
    )


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=textwrap.dedent("""
            Generate dbt intermediate union models using fabric_union_relations.

            Discovers all source YAML files matching _source_<base_source>_<variant>.yml
            under models/staging/, groups tables by entity name, and generates one
            int_<base_source>__<entity>_all.sql model per shared entity.

            Run from your dbt project root.
        """),
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument(
        "base_source",
        type=str,
        help=(
            "Base source name to union (e.g. 'qad'). "
            "Matches source files like _source_qad_us.yml, _source_qad_ca.yml."
        ),
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Preview what would be generated without writing any files.",
    )
    parser.add_argument(
        "--overwrite",
        action="store_true",
        help="Overwrite existing model files. Default is to skip existing files.",
    )
    parser.add_argument(
        "--source-column-name",
        type=str,
        default="source_system",
        help=(
            "Name of the column identifying the source variant for each row. "
            "Default: 'source_system'."
        ),
    )
    parser.add_argument(
        "--collation",
        type=str,
        default=DEFAULT_COLLATION,
        help=(
            "T-SQL collation to apply to text columns in the union. "
            f"Default: '{DEFAULT_COLLATION}'."
        ),
    )
    return parser.parse_args()


if __name__ == "__main__":
    args = parse_args()
    generate_union_models(args)
